name: "Publish documentation"
on:
  push:
    branches:
      - "main"
    
jobs:
  publish-documentation:
    permissions:
      id-token: "write"
      pages: "write"

    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Check out Git repository"
        uses: "actions/checkout@v3"

      - id: "setup-node"
        name: "Set up Node.js"
        uses: "actions/setup-node@v3"
        with:
            node-version: "20"

      - id: "install-dependencies"
        name: "Install Node.js dependencies"
        run: |
          npm install
      - id: "build"
        name: "Build documentation"
        run: |
          npm run docs
      - id: "upload-documentation"
        name: "Upload Pages artifact"
        uses: "actions/upload-pages-artifact@v2"
        with:
          path: "doc/"

      - id: "deployment"
        name: "Deploy documentation to GitHub Pages"
        uses: "actions/deploy-pages@v2"